Feature/crud
R-Kiselev/Flask-RESTful-API pull request #1
Opened 2024-09-19 07:28 UTC by R-Kiselev

2024-10-21 16:11 UTC, Sputnavi commented
Question our of curiousity: is it a good practice to have cards collection in account model? I see that it's lazy, but does it follow python best practices?

2024-10-21 16:36 UTC, Sputnavi requested changes

2024-10-21 16:36 UTC, Sputnavi commented on app/api/views.py
> +api.add_resource(BankAccountObjectRes, '/banks/accounts/<int:id>')
Bad url. It should be just `accounts/{id}` or` banks/{bankId}/accounts/{accountId}`. I think the first makes more sense as we discussed before

2024-10-21 16:36 UTC, Sputnavi commented on app/api/views.py
> +api.add_resource(ClientAccountObjectRes, '/clients/<int:client_id>/accounts/<int:account_id>')
Here you did the correct option, but it's just enough to have `account/{id}` endpoint as in previous comment, so you will reach accounts/{id} endpoint from many places as a final goal. So you retrieve account from `banks/{id}/accounts` or `client/{id}/account`, but recieve information about account by the same simple endpoint `accounts/{id}`.

2024-10-21 16:36 UTC, Sputnavi commented on app/api/views.py
> +api.add_resource(AccountCardObjectRes, '/accounts/cards/<int:id>')
Use the same "account" approach I suggested, this current flow is too hard

2024-10-21 16:36 UTC, Sputnavi commented on readme.md
> +You can paginate data using **page**, **per_page** and filter data by table fields.
Why have you decided to name it `per_page`?

2024-10-21 16:36 UTC, Sputnavi commented on app/commons/base_resources.py
> +            setattr(item, key, value)
Explaing this please. Does it split the item by properties and applies them on the item?

2024-10-21 16:36 UTC, Sputnavi commented on app/commons/base_resources.py
> +        db.session.add(item)
How doest it work? It says item, but I believe there's a collection of items

2024-10-21 16:36 UTC, Sputnavi commented on app/api/schemas/bank.py
> +        if not re.match(r"^[A-Za-z\s\-']+$", value):
I think there're many libraries in python which can take the responsibilities of such low level coding. I think it worth to spend some for it

2024-10-21 16:36 UTC, Sputnavi commented on app/api/schemas/bank.py
> +        if not re.match(r"^[A-Za-z\s\-']+$", value):
I'm okay with validation library, it's fine. I'm just not a big fan of writing custom regular expressions, especially when it's repeated in many places of your code. So it could be transfered to a single place, but looks like custom coding on a python, when you can find the library. The rich library set - the biggest power of python, so whenver you want to do something think about existing library first :)

2024-10-21 16:36 UTC, Sputnavi commented on app/api/resources/branches.py
> +class BankBranchObjectRes(BaseObjectResource):
Why `BankBranchObjectRes` when it could be just `BranchObjectRes`. Oviously there's everything about the bank domain in this code

2024-10-21 16:36 UTC, Sputnavi commented on app/api/resources/branches.py
> +        req = request.json
I noticed the repeation of the code from the base resource for almost no reason. Think how to avoid it, you have just few lines of code before main logic, but because of this difference you repeat more than needed. 

Do not forget to fix it in other endpoint handlers too.

2024-10-21 16:40 UTC, Sputnavi commented
To summarise.

I really like your recent changes, great level of improvement. It was really nice and pleasant to read your code, it's well structured and follows DRY principle. I really felt the power of python with tiny code for the whole application.

Keep doing your best effort on it. I believe it was the last review with change requests, I had mostly questions rather than suggestions.

Fix the comments and I'll approve this PR with providing next task 💪

2024-10-26 22:17 UTC, R-Kiselev commented on readme.md
> +You can paginate data using **page**, **per_page** and filter data by table fields.
According to the sqlalchemy documentation, you can paginate a query using the paginate method. This method returns a pagination object that has 'page' and 'per_page' fields. I named my variables to match the names in the documentation.

2024-10-26 22:44 UTC, R-Kiselev commented on app/commons/base_resources.py
> +            setattr(item, key, value)
Yes, you are correct. Assuming that `data` is a validated dictionary of information passed in the request, `data.items()` will return each key-value pair as a tuple. Now you want to update each `item` field passed in the request using the `settatr()` method.

2024-10-26 22:53 UTC, R-Kiselev commented on app/commons/base_resources.py
> +        db.session.add(item)
This is the `post` method. `data` is a dictionary of the `request` data, validated using the `schema`. `item` is a model class object (like Bank/Account/...) created using the ** operator to unpack dictionaries directly into keyword arguments. So it's just one item, not collection. This object is then simply added to the database.

2024-10-27 20:02 UTC, R-Kiselev commented on app/api/schemas/bank.py
> +        if not re.match(r"^[A-Za-z\s\-']+$", value):
In cases like this, regular expressions can offer simplicity and precision, especially when the library lacks built-in validation options for our specific requirements. In my case, I need custom validation logic for bank, city names, which means handling names like `Saint-Petersburg` supporting delimiters between words. Marshmallow offer fields with built-in validations  like `email` and `url`. But there isn’t a built-in option for validating names, and i couldn't find some lightweight libraries for validating such simple fields. 
By the way, the logic for processing validation was moved to the `commons` folder, leaving only decorators in the schemas.

2024-10-31 19:58 UTC, Sputnavi commented on readme.md
> +You can paginate data using **page**, **per_page** and filter data by table fields.
Please use pageNumber and pageSize naming. The library shouldn't dictate you how to do things for other layers

2024-10-31 20:05 UTC, Sputnavi approved these changes

2024-10-31 20:08 UTC, Sputnavi commented
The assessment of completed work will be with the following topics:
1) HTTP
2) REST
3) SOLID

2024-10-31 20:12 UTC, Sputnavi commented
Please merge PR with Squash option in dropdown menu, so the history on main branch will be clear with one commit and big description of changes

2024-10-31 20:12 UTC, Sputnavi commented
![image](https://github.com/user-attachments/assets/ba91134d-b267-42a8-b464-341717700070)

2024-10-31 21:03 UTC, merged