Feature/auth
R-Kiselev/Flask-RESTful-API pull request #2
Opened 2024-12-06 22:49 UTC by R-Kiselev

### Technical Requirements

1. **Add authentication/authorization to the existing API**
   - Use the **JWT standard** for authentication.

2. **Endpoints required:**
   - User registration.
   - User login.
   - Managing user roles.

3. **Authorization:**
   - Must be **role-based.**
   - Authorization should be checked for **every endpoint.**
   - Different roles should have different access to URLs.
   - Some roles should have access to the same URLs.
   - **Admin** must have access to all endpoints.

4. **Admin User:**
   - The application must have a **pre-generated Admin user.**
   - The Admin must have the ability to:
     - Block users.
     - Assign or remove roles for users.

2024-12-18 01:14 UTC, Sputnavi commented on app/models/user.py
> +
I think it worth to have some audit columns like RegisterDate, BlockedDate and so on
They could be useful for future features, statistics and troubleshooting.

2024-12-18 01:14 UTC, Sputnavi commented on app/flask_cli.py
> +        'email': os.getenv('ADMIN_EMAIL'),
Cool 👍  Like that you use configurable stuff, not hard coded

2024-12-18 01:14 UTC, Sputnavi commented on app/error_handling.py
> +            "error_type": "Database integrity error",
You shouldn't expose such technical errors in your response. Ideally it should the normal error for the final user. If I would see such response from an API I couldn't understand what the issue is, but would think that something wrong with your application, not my fault. I see from the code that there's just a typical duplicate problem, I think it worth to say for the API user that there's a duplicate, but not the error in DB.

2024-12-18 01:14 UTC, Sputnavi commented on app/error_handling.py
> +            "additional_info": "Please check your data for constraints violations."
Let's assume that user of your API doesn't have an access to your DB and code, he can't check for your structure and violations.

2024-12-18 01:14 UTC, Sputnavi commented
I haven't finished yet, will continue next time

2024-12-20 20:21 UTC, Sputnavi requested changes

2024-12-20 20:21 UTC, Sputnavi commented on app/api/resources/cards.py
> +            Card.id == kwargs.get('id')).first()
The function says that it's check for access, but there's some other logic which checks for existence. It's the part of the business logic. I think it makes sense just to inline in the endpoint function instead of decorator. Decorator is not a silber bullet for all cases. Decorator should control Role based auth (RBAC), but there you have some comlex logic that worth to be in bussiness logic - in service, but it's fine in your case to put it in the endpoint code as it's pretty simple in your case.

2024-12-20 20:21 UTC, Sputnavi commented on app/api/resources/accounts.py
> +ACCESS_DENIED_MESSAGE = "Access denied"
Interesting that you have that constant only here but not in other places

2024-12-20 20:21 UTC, Sputnavi commented on app/api/resources/accounts.py
>  class BankAccountListRes(BaseListResource):
Fix naming, remove bank here

2024-12-20 20:21 UTC, Sputnavi commented on app/api/resources/users.py
> +    method_decorators = [user_roles_required('admin'), jwt_required()]
Is it a python feature to assing decorators in this way or do you have custom code for handling that?

2024-12-20 20:21 UTC, Sputnavi commented on app/auth/utils.py
> +    return User.query.get(identity)
Really? JWT is used to avoid calls into DB but you still have that and even make it dangerous to make many calls within one request without intention.

2024-12-20 20:21 UTC, Sputnavi commented on app/auth/utils.py
> +    return User.query.get(identity)
All information you need should be put into JWT token during Authentication (Login). After that you're mostly not interested in DB calls.

2024-12-20 20:21 UTC, Sputnavi commented on app/auth/views.py
> +    if not email or not password:
Move it to the schema validation as you've used in other places

2024-12-20 20:21 UTC, Sputnavi commented on app/auth/views.py
> +    access_token = create_access_token(identity=user.id)
How does it understand what secret should be used to sign the token?

2024-12-20 20:21 UTC, Sputnavi commented on app/auth/views.py
> +    access_token = create_access_token(identity=user.id)
How does it understand what claims to add?

2024-12-20 20:21 UTC, Sputnavi commented on app/auth/views.py
> +    access_token = create_access_token(identity=user.id)
I see that there're a lot of missing moments as for me

2024-12-20 20:25 UTC, Sputnavi commented on app/error_handling.py
> +            "error_type": "Database integrity error",
By they way you can expose technical details only during development, so you can and some checks here for development environment which comes from environment variables so it makes you life easier and secures your app after Prod release.

2024-12-23 16:43 UTC, R-Kiselev commented on app/models/user.py
> +
Done. Added `registered_on`, `blocked_on`, `last_login_date` for user.

2024-12-23 16:45 UTC, R-Kiselev commented on app/error_handling.py
> +            "error_type": "Database integrity error",
Changed this so that users and developers now get different error messages depending on the environment.

2024-12-23 17:09 UTC, R-Kiselev commented on app/auth/utils.py
> +    return User.query.get(identity)
This function is used only in `/whoami` endpoint to get info about current user and jwt claims. It is not used in other endpoints.

2024-12-23 17:10 UTC, R-Kiselev commented on app/api/resources/accounts.py
> +ACCESS_DENIED_MESSAGE = "Access denied"
Moved this constant into `/commons/constants.py`

2024-12-23 17:19 UTC, R-Kiselev commented on app/api/resources/users.py
> +    method_decorators = [user_roles_required('admin'), jwt_required()]
No, this is not custom code. This is a built-in feature of the Flask-RESTful library. It allows you to apply decorators to resource methods in a more declarative way. All decorators in the list are applied to every method in the resource. This approach avoids repetition and makes your code more readable, since you don’t have to manually assign decorators to each function.

2024-12-23 17:35 UTC, R-Kiselev commented on app/auth/views.py
> +    access_token = create_access_token(identity=user.id)
The `JWT_SECRET_KEY` from the `.env` file is used to sign tokens. In Flask, configuration values, including the secret key, are typically loaded when the application starts. These values are stored in Flask's config object. During the `configure_extensions` function in `app.py`, the `jwt.init_app(app)` method is called, which initializes the JWT manager. This initialization process allows the extension to access the `JWT_SECRET_KEY` from the config object.

`additional_claims_loader`
This decorator sets the callback function used to add additional claims when creating a JWT. The claims returned by this function will be merged with any claims passed in via the additional_claims argument to create_access_token().

2025-01-02 10:22 UTC, Sputnavi commented
The rest is good for me, let's complete it

2025-01-13 12:22 UTC, merged